version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_ENABLED: "true"
    depends_on:
      - mongo

  node:
    image: demo_node_app:latest   # ✅ use your built image
    container_name: node_app
    restart: always
    ports:
      - "5050:5050"
    environment:
      MONGO_URL: mongodb://admin:qwerty@mongo:27017/?authSource=admin
    depends_on:
      - mongo